name: Monthly Release

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    name: Create monthly release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.create.outputs.tag }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Create release
        id: create
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(date +"%B-%Y" | tr '[:upper:]' '[:lower:]')
          gh release create "$tag" --target "$GITHUB_SHA" --generate-notes --title "$tag"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

  publish:
    needs: release
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/publish.yml
    with:
      tag: ${{ needs.release.outputs.tag }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
